# Este arquivo é um de um workflow do GitHub Actions para aplicar configurações de rede em um cluster EKS na AWS.
# Ele é acionado quando há um push na branch main ou quando é executado manualmente.
# O workflow configura as credenciais da AWS, faz o checkout do repositório, configura o contexto do Kubernetes e aplica os recursos de rede.

name: "4- Deploy Networking"

on:
  push:
    branches: ["main"]
    paths:
      - 'kubernetes/networking/**'
      - "!kubernetes/networking/telemetry/**"
  workflow_dispatch:

jobs:
  deploy-networking:
    name: "Deploy Networking"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Configure Kubernetes Context"
        run: |
          aws eks --region us-east-1 update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: "Apply networking Resources"
        run: |
          echo "Aplicando recursos de networking..."
          kubectl apply -f kubernetes/networking/gateway/
          kubectl apply -f kubernetes/networking/virtual-services/
          
          # Verificar recursos aplicados
          kubectl get gateways --all-namespaces
          kubectl get virtualservices --all-namespaces