# Este arquivo é um de um workflow do GitHub Actions para implantar o Tempo em um cluster EKS na AWS.
# Ele é acionado quando há um push na branch main ou quando é executado manualmente.
# O workflow configura as credenciais da AWS, faz o checkout do repositório, configura o contexto do Kubernetes e implanta o Tempo usando o Helm.
name: "9 - Deploy Tempo"

on:
  push:
    branches: ["main"]
    paths: ["kubernetes/monitoring/tempo.yaml"]
  workflow_dispatch:

jobs:
  deploy-tempo:
    name: "Deploy Tempo"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Configure Kubernetes Context"
        run: |
          aws eks --region us-east-1 update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: "Create monitoring namespace if not exists"
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: "Add Helm repositories"
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: "Install Tempo"
        run: |
          echo "Instalando Tempo..."
          helm upgrade --install tempo grafana/tempo-distributed --version 1.33.0 -f kubernetes/monitoring/tempo.yaml --namespace monitoring
          
      - name: "Verify Tempo Deployment"
        run: |
          kubectl get pods -n monitoring -l app=tempo