# Este arquivo é um exemplo de um workflow do GitHub Actions para aplicar configurações do Terraform em um cluster EKS na AWS.
# Ele é acionado quando há um push na branch main ou quando é executado manualmente.
# O workflow configura as credenciais da AWS, faz o checkout do repositório, inicializa o Terraform, gera um plano e aplica as mudanças.
# O arquivo assume que as credenciais da AWS e o nome do bucket S3 estão armazenados como segredos no repositório do GitHub.
# O bucket S3 é usado para armazenar o estado do Terraform.
# O arquivo também assume que o Terraform está instalado e configurado corretamente no ambiente de execução.
# Certifique-se de que o bucket S3 e o arquivo de estado do Terraform estejam configurados corretamente antes de executar este workflow.
# Além disso, é importante criar as credenciais da AWS e o bucket S3 antes de executar o workflow.
# Certifique-se de que o bucket S3 e o arquivo de estado do Terraform estejam configurados corretamente antes de executar este workflow.
name: "Cuidado -Terraform destroy"
on:
    workflow_dispatch: 
    
jobs: 
  terraform:
    name: "Terraform destroy"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Init"
        working-directory: ./infraestrutura/eks
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}" -backend-config="region=us-east-1"

      - name: Terraform Destroy 
        working-directory: ./infraestrutura/eks
        run: terraform destroy --auto-approve